### ISSUE TITLE
Russian localization 

### ISSUE THREAD

**Issue by alwwwd** [crystall1nedev/Malachite#4]
Hi! How can i help with localize your app to russian language? I’m a native russian speaking

**Comment by crystall1nedev** [comment]
Localization is now possible with the past few commits to the `develop` branch of Malachite. To get started, you'll want to head into the `Localization.xcstrings` file and add a new language:

<img width="512" alt="Screenshot 2024-10-14 at 01 33 07" src="https://github.com/user-attachments/assets/062a2e37-a206-4941-838e-eedbb6507279">

Once the new language is added, just translate away!
